import type { Integration, User, AuditLog, DashboardStats } from "./types";

export const mockIntegrations: Integration[] = [
  {
    id: "1",
    nomi: "Asaka Bank bilan to'lov tizimi integratsiyasi",
    vazirlik: "Asaka Bank",
    huquqiyAsos: "O'zR PV 2023-yil 15-son qarori",
    texnologiya: "REST",
    status: "Active",
    sana: "2024-01-15",
    muddat: "2025-01-15",
    tavsif: "Bank to'lovlarini boshqarish uchun integratsiya",
    tashkilotTuri: "Bank",
    sorovlarOrtachaOylik: 15000,
    qaysiTashkilotTomondan: "Markaziy Bank",
    axborotTizimiNomi: "To'lov tizimi",
    tashkilotShakli: "Xususiy tashkilot",
    asosiyMaqsad:
      "Markaziy Bank va Asaka Bank o'rtasida to'lov operatsiyalarini avtomatlashtirish, real vaqtda tranzaksiyalarni kuzatish, moliyaviy ma'lumotlarni tekshirish va mijozlar uchun tez va xavfsiz to'lov xizmatlarini taqdim etish uchun integratsiya tizimini yaratish.",
    normativHuquqiyHujjat: "O'zR PV 2023-yil 15-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Sorov-javob",
    mspdManzil: "mspd.cbu.uz/api/payments",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    nomi: "Xalq Banki bilan ma'lumot almashish",
    vazirlik: "Xalq Banki",
    huquqiyAsos: "O'zR PV 2023-yil 28-son qarori",
    texnologiya: "SOAP",
    status: "Test",
    sana: "2024-02-01",
    muddat: "2025-02-01",
    tavsif: "Bank mijozlari ma'lumotlarini olish",
    tashkilotTuri: "Bank",
    sorovlarOrtachaOylik: 8500,
    qaysiTashkilotTomondan: "Xalq Banki",
    axborotTizimiNomi: "Mijozlar ma'lumotlari tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad:
      "Xalq Banki va Markaziy Bank o'rtasida mijoz ma'lumotlarini tekshirish, kredit tarixini olish, moliyaviy holatni baholash va mijozlar uchun shaxsiy ma'lumotlarni himoya qilish uchun xavfsiz ma'lumot almashish tizimini yaratish.",
    normativHuquqiyHujjat: "O'zR PV 2023-yil 28-son qarori",
    texnologikYoriknomaMavjudligi: false,
    maqlumotAlmashishSharti: "Push",
    mspdManzil: "mspd.cbu.uz/api/customers",
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-02-01T09:00:00Z",
  },
  {
    id: "3",
    nomi: "Agro Bank hisobot tizimi",
    vazirlik: "Agro Bank",
    huquqiyAsos: "O'zR PV 2023-yil 42-son qarori",
    texnologiya: "File exchange",
    status: "Archived",
    sana: "2024-03-10",
    muddat: "2025-03-10",
    tavsif: "Oylik bank hisobotlarini yuborish",
    tashkilotTuri: "Bank",
    sorovlarOrtachaOylik: 1200,
    qaysiTashkilotTomondan: "Agro Bank",
    axborotTizimiNomi: "Hisobot tizimi",
    tashkilotShakli: "Xususiy tashkilot",
    asosiyMaqsad: "Oylik hisobotlarni yuborish",
    normativHuquqiyHujjat: "O'zR PV 2023-yil 42-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Fayl almashinuvi",
    mspdManzil: "mspd.cbu.uz/files/reports",
    createdAt: "2024-03-10T14:00:00Z",
    updatedAt: "2024-03-10T14:00:00Z",
  },
  {
    id: "4",
    nomi: "Ipoteka Bank REST API integratsiyasi",
    vazirlik: "Ipoteka Bank",
    huquqiyAsos: "O'zR PV 2024-yil 01-son qarori",
    texnologiya: "REST",
    status: "Active",
    sana: "2024-03-01",
    muddat: "2025-03-01",
    tavsif: "Ipoteka kreditlari ma'lumotlari",
    tashkilotTuri: "Bank",
    sorovlarOrtachaOylik: 22000,
    qaysiTashkilotTomondan: "Markaziy Bank",
    axborotTizimiNomi: "Ipoteka tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Ipoteka kreditlarini boshqarish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 01-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Sorov-javob",
    mspdManzil: "mspd.cbu.uz/api/mortgage",
    createdAt: "2024-03-01T11:45:00Z",
    updatedAt: "2024-03-01T11:45:00Z",
  },
  {
    id: "5",
    nomi: "Sberbank bilan valyuta kurslari integratsiyasi",
    vazirlik: "Sberbank",
    huquqiyAsos: "O'zR PV 2024-yil 12-son qarori",
    texnologiya: "MQ",
    status: "Test",
    sana: "2024-04-15",
    muddat: "2025-04-15",
    tavsif: "Valyuta kurslarini real vaqtda olish",
    tashkilotTuri: "Xorijiy bank",
    sorovlarOrtachaOylik: 50000,
    qaysiTashkilotTomondan: "Sberbank",
    axborotTizimiNomi: "Valyuta kurslari tizimi",
    tashkilotShakli: "Xorijiy tashkilot",
    asosiyMaqsad: "Valyuta kurslarini real vaqtda olish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 12-son qarori",
    texnologikYoriknomaMavjudligi: false,
    maqlumotAlmashishSharti: "Push",
    mspdManzil: "mspd.cbu.uz/mq/exchange-rates",
    createdAt: "2024-04-15T08:30:00Z",
    updatedAt: "2024-04-15T08:30:00Z",
  },
  {
    id: "6",
    nomi: "Kapital Bank kredit tizimi",
    vazirlik: "Kapital Bank",
    huquqiyAsos: "O'zR PV 2024-yil 18-son qarori",
    texnologiya: "REST",
    status: "Active",
    sana: "2024-05-01",
    muddat: "2025-05-01",
    tavsif: "Kredit ma'lumotlarini tekshirish",
    tashkilotTuri: "Bank",
    sorovlarOrtachaOylik: 18000,
    qaysiTashkilotTomondan: "Markaziy Bank",
    axborotTizimiNomi: "Kredit tizimi",
    tashkilotShakli: "Xususiy tashkilot",
    asosiyMaqsad: "Kredit ma'lumotlarini tekshirish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 18-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Sorov-javob",
    mspdManzil: "mspd.cbu.uz/api/credits",
    createdAt: "2024-05-01T12:00:00Z",
    updatedAt: "2024-05-01T12:00:00Z",
  },
  {
    id: "7",
    nomi: "Davlat soliq xizmati integratsiyasi",
    vazirlik: "Davlat soliq xizmati",
    huquqiyAsos: "O'zR PV 2024-yil 25-son qarori",
    texnologiya: "REST",
    status: "Active",
    sana: "2024-06-01",
    muddat: "2025-06-01",
    tavsif: "Soliq ma'lumotlarini almashish",
    tashkilotTuri: "Davlat tashkiloti",
    sorovlarOrtachaOylik: 25000,
    qaysiTashkilotTomondan: "Davlat soliq xizmati",
    axborotTizimiNomi: "Soliq tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Soliq ma'lumotlarini avtomatik almashish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 25-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Sorov-javob",
    mspdManzil: "mspd.cbu.uz/api/tax",
    createdAt: "2024-06-01T09:00:00Z",
    updatedAt: "2024-06-01T09:00:00Z",
  },
  {
    id: "8",
    nomi: "Milliy bank integratsiyasi",
    vazirlik: "Milliy bank",
    huquqiyAsos: "O'zR PV 2024-yil 30-son qarori",
    texnologiya: "SOAP",
    status: "Test",
    sana: "2024-07-15",
    muddat: "2025-07-15",
    tavsif: "Valyuta operatsiyalari ma'lumotlari",
    tashkilotTuri: "Bank",
    sorovlarOrtachaOylik: 35000,
    qaysiTashkilotTomondan: "Milliy bank",
    axborotTizimiNomi: "Valyuta tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Valyuta operatsiyalarini kuzatish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 30-son qarori",
    texnologikYoriknomaMavjudligi: false,
    maqlumotAlmashishSharti: "Push",
    mspdManzil: "mspd.cbu.uz/soap/currency",
    createdAt: "2024-07-15T14:30:00Z",
    updatedAt: "2024-07-15T14:30:00Z",
  },
  {
    id: "9",
    nomi: "Davlat statistika qo'mitasi hisobotlari",
    vazirlik: "Davlat statistika qo'mitasi",
    huquqiyAsos: "O'zR PV 2024-yil 35-son qarori",
    texnologiya: "File exchange",
    status: "Active",
    sana: "2024-08-01",
    muddat: "2025-08-01",
    tavsif: "Statistik ma'lumotlarni yuborish",
    tashkilotTuri: "Davlat tashkiloti",
    sorovlarOrtachaOylik: 5000,
    qaysiTashkilotTomondan: "Davlat statistika qo'mitasi",
    axborotTizimiNomi: "Statistika tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Statistik hisobotlarni avtomatik yuborish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 35-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Fayl almashinuvi",
    mspdManzil: "mspd.cbu.uz/files/statistics",
    createdAt: "2024-08-01T11:15:00Z",
    updatedAt: "2024-08-01T11:15:00Z",
  },
  {
    id: "10",
    nomi: "Davlat xavfsizlik xizmati integratsiyasi",
    vazirlik: "Davlat xavfsizlik xizmati",
    huquqiyAsos: "O'zR PV 2024-yil 40-son qarori",
    texnologiya: "MQ",
    status: "Test",
    sana: "2024-09-01",
    muddat: "2025-09-01",
    tavsif: "Xavfsizlik ma'lumotlarini almashish",
    tashkilotTuri: "Davlat tashkiloti",
    sorovlarOrtachaOylik: 12000,
    qaysiTashkilotTomondan: "Davlat xavfsizlik xizmati",
    axborotTizimiNomi: "Xavfsizlik tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Xavfsizlik ma'lumotlarini real vaqtda almashish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 40-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Push",
    mspdManzil: "mspd.cbu.uz/mq/security",
    createdAt: "2024-09-01T16:45:00Z",
    updatedAt: "2024-09-01T16:45:00Z",
  },
  {
    id: "11",
    nomi: "Davlat kadastr xizmati integratsiyasi",
    vazirlik: "Davlat kadastr xizmati",
    huquqiyAsos: "O'zR PV 2024-yil 45-son qarori",
    texnologiya: "REST",
    status: "Active",
    sana: "2024-10-01",
    muddat: "2025-10-01",
    tavsif: "Kadastr ma'lumotlarini tekshirish",
    tashkilotTuri: "Davlat tashkiloti",
    sorovlarOrtachaOylik: 8000,
    qaysiTashkilotTomondan: "Davlat kadastr xizmati",
    axborotTizimiNomi: "Kadastr tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Kadastr ma'lumotlarini tekshirish va tasdiqlash",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 45-son qarori",
    texnologikYoriknomaMavjudligi: false,
    maqlumotAlmashishSharti: "Sorov-javob",
    mspdManzil: "mspd.cbu.uz/api/cadastre",
    createdAt: "2024-10-01T10:20:00Z",
    updatedAt: "2024-10-01T10:20:00Z",
  },
  {
    id: "12",
    nomi: "Davlat arxitektura va qurilish nazorati",
    vazirlik: "Davlat arxitektura va qurilish nazorati",
    huquqiyAsos: "O'zR PV 2024-yil 50-son qarori",
    texnologiya: "SOAP",
    status: "Archived",
    sana: "2024-11-01",
    muddat: "2025-11-01",
    tavsif: "Qurilish litsenziyalarini tekshirish",
    tashkilotTuri: "Davlat tashkiloti",
    sorovlarOrtachaOylik: 3000,
    qaysiTashkilotTomondan: "Davlat arxitektura va qurilish nazorati",
    axborotTizimiNomi: "Qurilish tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Qurilish litsenziyalarini tekshirish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 50-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Fayl almashinuvi",
    mspdManzil: "mspd.cbu.uz/soap/construction",
    createdAt: "2024-11-01T13:10:00Z",
    updatedAt: "2024-11-01T13:10:00Z",
  },
  {
    id: "13",
    nomi: "Davlat ekologik nazorat xizmati",
    vazirlik: "Davlat ekologik nazorat xizmati",
    huquqiyAsos: "O'zR PV 2024-yil 55-son qarori",
    texnologiya: "REST",
    status: "Active",
    sana: "2024-12-01",
    muddat: "2025-12-01",
    tavsif: "Ekologik monitoring ma'lumotlari",
    tashkilotTuri: "Davlat tashkiloti",
    sorovlarOrtachaOylik: 6000,
    qaysiTashkilotTomondan: "Davlat ekologik nazorat xizmati",
    axborotTizimiNomi: "Ekologiya tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Ekologik monitoring ma'lumotlarini kuzatish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 55-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Push",
    mspdManzil: "mspd.cbu.uz/api/ecology",
    createdAt: "2024-12-01T08:30:00Z",
    updatedAt: "2024-12-01T08:30:00Z",
  },
  {
    id: "14",
    nomi: "Davlat mehnat va aholini ijtimoiy muhofaza qilish vazirligi",
    vazirlik: "Davlat mehnat va aholini ijtimoiy muhofaza qilish vazirligi",
    huquqiyAsos: "O'zR PV 2024-yil 60-son qarori",
    texnologiya: "File exchange",
    status: "Test",
    sana: "2024-12-15",
    muddat: "2025-12-15",
    tavsif: "Ijtimoiy sug'urta ma'lumotlari",
    tashkilotTuri: "Davlat tashkiloti",
    sorovlarOrtachaOylik: 15000,
    qaysiTashkilotTomondan:
      "Davlat mehnat va aholini ijtimoiy muhofaza qilish vazirligi",
    axborotTizimiNomi: "Ijtimoiy sug'urta tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Ijtimoiy sug'urta ma'lumotlarini almashish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 60-son qarori",
    texnologikYoriknomaMavjudligi: false,
    maqlumotAlmashishSharti: "Fayl almashinuvi",
    mspdManzil: "mspd.cbu.uz/files/social-insurance",
    createdAt: "2024-12-15T12:00:00Z",
    updatedAt: "2024-12-15T12:00:00Z",
  },
  {
    id: "15",
    nomi: "Davlat transport vazirligi integratsiyasi",
    vazirlik: "Davlat transport vazirligi",
    huquqiyAsos: "O'zR PV 2024-yil 65-son qarori",
    texnologiya: "MQ",
    status: "Active",
    sana: "2024-12-20",
    muddat: "2025-12-20",
    tavsif: "Transport vositalari ro'yxati",
    tashkilotTuri: "Davlat tashkiloti",
    sorovlarOrtachaOylik: 20000,
    qaysiTashkilotTomondan: "Davlat transport vazirligi",
    axborotTizimiNomi: "Transport tizimi",
    tashkilotShakli: "Davlat tashkiloti",
    asosiyMaqsad: "Transport vositalari ma'lumotlarini kuzatish",
    normativHuquqiyHujjat: "O'zR PV 2024-yil 65-son qarori",
    texnologikYoriknomaMavjudligi: true,
    maqlumotAlmashishSharti: "Push",
    mspdManzil: "mspd.cbu.uz/mq/transport",
    createdAt: "2024-12-20T15:45:00Z",
    updatedAt: "2024-12-20T15:45:00Z",
  },
];

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Alisher Karimov",
    email: "a.karimov@cbu.uz",
    role: "Administrator",
  },
  {
    id: "2",
    name: "Nodira Tosheva",
    email: "n.tosheva@cbu.uz",
    role: "Operator",
  },
  {
    id: "3",
    name: "Bobur Rahimov",
    email: "b.rahimov@cbu.uz",
    role: "Viewer",
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: "1",
    userId: "1",
    userName: "Alisher Karimov",
    action: "Integratsiya yaratildi",
    integrationId: "1",
    integrationName: "Asaka Bank bilan to'lov tizimi integratsiyasi",
    timestamp: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    userId: "2",
    userName: "Nodira Tosheva",
    action: "Integratsiya tahrirlandi",
    integrationId: "2",
    integrationName: "Xalq Banki bilan ma'lumot almashish",
    changes: { status: "Test" },
    timestamp: "2024-02-01T15:30:00Z",
  },
];

export const extendedAuditLogs: AuditLog[] = [
  {
    id: "1",
    userId: "1",
    userName: "Alisher Karimov",
    action: "Integratsiya yaratildi",
    integrationId: "1",
    integrationName: "Asaka Bank bilan to'lov tizimi integratsiyasi",
    timestamp: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    userId: "2",
    userName: "Nodira Tosheva",
    action: "Integratsiya tahrirlandi",
    integrationId: "2",
    integrationName: "Xalq Banki bilan ma'lumot almashish",
    changes: { status: "Active → Test", texnologiya: "REST → SOAP" },
    timestamp: "2024-02-01T15:30:00Z",
  },
  {
    id: "3",
    userId: "1",
    userName: "Alisher Karimov",
    action: "Integratsiya arxivlandi",
    integrationId: "3",
    integrationName: "Agro Bank hisobot tizimi",
    changes: { status: "Active → Archived" },
    timestamp: "2024-02-15T09:15:00Z",
  },
  {
    id: "4",
    userId: "3",
    userName: "Bobur Rahimov",
    action: "Integratsiya ko'rildi",
    integrationId: "1",
    integrationName: "Asaka Bank bilan to'lov tizimi integratsiyasi",
    timestamp: "2024-02-20T14:22:00Z",
  },
  {
    id: "5",
    userId: "2",
    userName: "Nodira Tosheva",
    action: "Integratsiya yaratildi",
    integrationId: "4",
    integrationName: "Ipoteka Bank REST API integratsiyasi",
    timestamp: "2024-03-01T11:45:00Z",
  },
  {
    id: "6",
    userId: "1",
    userName: "Alisher Karimov",
    action: "Tizim sozlamalari o'zgartirildi",
    changes: {
      monitoring_interval: "5min → 3min",
      alert_threshold: "95% → 98%",
    },
    timestamp: "2024-03-05T16:30:00Z",
  },
  {
    id: "7",
    userId: "2",
    userName: "Nodira Tosheva",
    action: "Integratsiya tahrirlandi",
    integrationId: "1",
    integrationName: "Asaka Bank bilan to'lov tizimi integratsiyasi",
    changes: { muddat: "2025-01-15 → 2025-06-15", tavsif: "Yangilandi" },
    timestamp: "2024-03-10T13:20:00Z",
  },
  {
    id: "8",
    userId: "1",
    userName: "Alisher Karimov",
    action: "Integratsiya yaratildi",
    integrationId: "5",
    integrationName: "Sberbank bilan valyuta kurslari integratsiyasi",
    timestamp: "2024-04-15T08:30:00Z",
  },
  {
    id: "9",
    userId: "3",
    userName: "Bobur Rahimov",
    action: "Integratsiya ko'rildi",
    integrationId: "2",
    integrationName: "Xalq Banki bilan ma'lumot almashish",
    timestamp: "2024-04-20T11:15:00Z",
  },
  {
    id: "10",
    userId: "2",
    userName: "Nodira Tosheva",
    action: "Integratsiya tahrirlandi",
    integrationId: "5",
    integrationName: "Sberbank bilan valyuta kurslari integratsiyasi",
    changes: { status: "Test → Active", texnologiya: "MQ" },
    timestamp: "2024-04-25T14:45:00Z",
  },
  {
    id: "11",
    userId: "1",
    userName: "Alisher Karimov",
    action: "Integratsiya yaratildi",
    integrationId: "6",
    integrationName: "Kapital Bank kredit tizimi",
    timestamp: "2024-05-01T12:00:00Z",
  },
  {
    id: "12",
    userId: "3",
    userName: "Bobur Rahimov",
    action: "Integratsiya ko'rildi",
    integrationId: "4",
    integrationName: "Ipoteka Bank REST API integratsiyasi",
    timestamp: "2024-05-05T09:30:00Z",
  },
  {
    id: "13",
    userId: "2",
    userName: "Nodira Tosheva",
    action: "Integratsiya tahrirlandi",
    integrationId: "6",
    integrationName: "Kapital Bank kredit tizimi",
    changes: {
      tavsif: "Kredit ma'lumotlarini tekshirish va yangilash",
    },
    timestamp: "2024-05-10T16:20:00Z",
  },
  {
    id: "14",
    userId: "1",
    userName: "Alisher Karimov",
    action: "Integratsiya ko'rildi",
    integrationId: "5",
    integrationName: "Sberbank bilan valyuta kurslari integratsiyasi",
    timestamp: "2024-05-15T10:45:00Z",
  },
  {
    id: "15",
    userId: "2",
    userName: "Nodira Tosheva",
    action: "Integratsiya tahrirlandi",
    integrationId: "2",
    integrationName: "Xalq Banki bilan ma'lumot almashish",
    changes: { muddat: "2025-02-01 → 2025-08-01" },
    timestamp: "2024-05-20T13:10:00Z",
  },
  {
    id: "16",
    userId: "3",
    userName: "Bobur Rahimov",
    action: "Integratsiya ko'rildi",
    integrationId: "6",
    integrationName: "Kapital Bank kredit tizimi",
    timestamp: "2024-05-25T15:30:00Z",
  },
  {
    id: "17",
    userId: "1",
    userName: "Alisher Karimov",
    action: "Tizim sozlamalari o'zgartirildi",
    changes: {
      backup_frequency: "Daily → Hourly",
      log_retention: "30 days → 90 days",
    },
    timestamp: "2024-06-01T11:00:00Z",
  },
  {
    id: "18",
    userId: "2",
    userName: "Nodira Tosheva",
    action: "Integratsiya arxivlandi",
    integrationId: "3",
    integrationName: "Agro Bank hisobot tizimi",
    changes: { status: "Archived → Deleted" },
    timestamp: "2024-06-05T14:25:00Z",
  },
  {
    id: "19",
    userId: "3",
    userName: "Bobur Rahimov",
    action: "Integratsiya ko'rildi",
    integrationId: "1",
    integrationName: "Asaka Bank bilan to'lov tizimi integratsiyasi",
    timestamp: "2024-06-10T08:15:00Z",
  },
  {
    id: "20",
    userId: "1",
    userName: "Alisher Karimov",
    action: "Integratsiya tahrirlandi",
    integrationId: "4",
    integrationName: "Ipoteka Bank REST API integratsiyasi",
    changes: { texnologiya: "REST → SOAP" },
    timestamp: "2024-06-15T12:40:00Z",
  },
];

export interface IntegrationVersion {
  id: string;
  integrationId: string;
  version: number;
  data: Partial<Integration>;
  changedBy: string;
  changedAt: string;
  changeReason?: string;
}

export const mockVersionHistory: IntegrationVersion[] = [
  {
    id: "v1",
    integrationId: "1",
    version: 1,
    data: {
      nomi: "Asaka Bank bilan to'lov tizimi integratsiyasi",
      vazirlik: "Asaka Bank",
      status: "Test",
      texnologiya: "REST",
      muddat: "2024-12-31",
    },
    changedBy: "Alisher Karimov",
    changedAt: "2024-01-15T10:00:00Z",
    changeReason: "Dastlabki yaratish",
  },
  {
    id: "v2",
    integrationId: "1",
    version: 2,
    data: {
      status: "Active",
      muddat: "2025-01-15",
    },
    changedBy: "Nodira Tosheva",
    changedAt: "2024-01-20T14:30:00Z",
    changeReason: "Test muvaffaqiyatli yakunlandi, faollashtirish",
  },
  {
    id: "v3",
    integrationId: "1",
    version: 3,
    data: {
      muddat: "2025-06-15",
      tavsif: "Bank to'lovlarini boshqarish uchun integratsiya - yangilangan",
    },
    changedBy: "Nodira Tosheva",
    changedAt: "2024-03-10T13:20:00Z",
    changeReason: "Muddat uzaytirildi va tavsif yangilandi",
  },
  {
    id: "v4",
    integrationId: "2",
    version: 1,
    data: {
      nomi: "Xalq Banki bilan ma'lumot almashish",
      vazirlik: "Xalq Banki",
      status: "Active",
      texnologiya: "REST",
    },
    changedBy: "Nodira Tosheva",
    changedAt: "2024-02-01T09:00:00Z",
    changeReason: "Dastlabki yaratish",
  },
  {
    id: "v5",
    integrationId: "2",
    version: 2,
    data: {
      status: "Test",
      texnologiya: "SOAP",
    },
    changedBy: "Nodira Tosheva",
    changedAt: "2024-02-01T15:30:00Z",
    changeReason: "Texnologiya o'zgartirildi va test holatiga o'tkazildi",
  },
  {
    id: "v6",
    integrationId: "2",
    version: 3,
    data: {
      muddat: "2025-08-01",
    },
    changedBy: "Nodira Tosheva",
    changedAt: "2024-05-20T13:10:00Z",
    changeReason: "Muddat uzaytirildi",
  },
  {
    id: "v7",
    integrationId: "4",
    version: 1,
    data: {
      nomi: "Ipoteka Bank REST API integratsiyasi",
      vazirlik: "Ipoteka Bank",
      status: "Active",
      texnologiya: "REST",
    },
    changedBy: "Nodira Tosheva",
    changedAt: "2024-03-01T11:45:00Z",
    changeReason: "Dastlabki yaratish",
  },
  {
    id: "v8",
    integrationId: "4",
    version: 2,
    data: {
      texnologiya: "REST",
    },
    changedBy: "Alisher Karimov",
    changedAt: "2024-06-15T12:40:00Z",
    changeReason: "API texnologiyasi yangilandi",
  },
  {
    id: "v9",
    integrationId: "5",
    version: 1,
    data: {
      nomi: "Sberbank bilan valyuta kurslari integratsiyasi",
      vazirlik: "Sberbank",
      status: "Test",
      texnologiya: "MQ",
    },
    changedBy: "Alisher Karimov",
    changedAt: "2024-04-15T08:30:00Z",
    changeReason: "Dastlabki yaratish",
  },
  {
    id: "v10",
    integrationId: "5",
    version: 2,
    data: {
      status: "Active",
    },
    changedBy: "Nodira Tosheva",
    changedAt: "2024-04-25T14:45:00Z",
    changeReason: "Test muvaffaqiyatli yakunlandi",
  },
  {
    id: "v11",
    integrationId: "6",
    version: 1,
    data: {
      nomi: "Kapital Bank kredit tizimi",
      vazirlik: "Kapital Bank",
      status: "Active",
      texnologiya: "REST",
    },
    changedBy: "Alisher Karimov",
    changedAt: "2024-05-01T12:00:00Z",
    changeReason: "Dastlabki yaratish",
  },
  {
    id: "v12",
    integrationId: "6",
    version: 2,
    data: {
      tavsif: "Kredit ma'lumotlarini tekshirish va yangilash",
    },
    changedBy: "Nodira Tosheva",
    changedAt: "2024-05-10T16:20:00Z",
    changeReason: "Funksionallik kengaytirildi",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalIntegrations: 6,
  activeIntegrations: 3,
  testIntegrations: 2,
  archivedIntegrations: 1,
  integrationsByMinistry: {
    "Asaka Bank": 1,
    "Xalq Banki": 1,
    "Agro Bank": 1,
    "Ipoteka Bank": 1,
    Sberbank: 1,
    "Kapital Bank": 1,
  },
  integrationsByTechnology: {
    REST: 3,
    SOAP: 1,
    "File exchange": 1,
    MQ: 1,
  },
  recentActivity: extendedAuditLogs,
};
